### ISSUE TITLE
Delegate method didSelectSegmentAtIndex with multiple SMSegmentView

### ISSUE THREAD

**Issue by pcs289** [sima-11/SMSegmentView#1]
The delegate method should include a SMSegmentView parameter to know which SMSegmentView (in case there's more than one) triggered the action.

**Comment by sima-11** [comment]
@pcs289 Yes, you're right. Completely missed that point. Have pushed my changes. Thanks for the comment, mate! ;)

**Comment by pcs289** [comment]
ty @allenbryan11 :)
