### ISSUE TITLE
Error with crash log

### ISSUE THREAD

**Issue by AlexLb** [sima-11/SMSegmentView#11]
Hello, 

I published my app, but it had refused.
When I symbolicate the crash log, I have this line on the exception code :+1: 

SMSegment.(title.materializeForSet).(closure #1) (in Honi) (SMSegment.swift:61)

I don't understand, maybe help me please before I post again my app.
Because all test on all device works with TestFlight, so I was surprised by Apple, they say to me "Crash on launch"

Thanks

**Comment by sima-11** [comment]
@AlexLb,

Apologise for this very late reply. 

I'm afraid that I couldn't reproduce the issue. Some people mentioned this may relate to protocols in the beta version of Xcode 7. I'm working on a new version of the framework, which deprecates the use of protocols. Hopefully this would solve the issue.
