### ISSUE TITLE
SMSegmentViewDelegate error

### ISSUE THREAD

**Issue by tobyapp** [sima-11/SMSegmentView#12]
i have the following:

![screen shot 2016-02-11 at 22 30 56](https://cloud.githubusercontent.com/assets/9108033/12992913/2fe4478c-d10f-11e5-9f4b-0c2f4151a2d7.png)

but have added:

```
func segmentView(segmentView: SMSegmentView, didSelectSegmentAtIndex index: Int) {
    print(index)
}
```

any ideas?

**Comment by Ashu** [comment]
I have fixed this issue here https://github.com/allenbryan11/SMSegmentView/pull/13

Just add `@objc` attribute to Swift protocol.

**Comment by tobyapp** [comment]
Ok thanks!

**Comment by santaj** [comment]
Sorry can you please explain where to add @objc attribute? unknown areas for me! I have the same fault. Thanks!

**Comment by sima-11** [comment]
@santaj Guess I missed your comment for some reason, sorry about that. This delegate has actually been removed for quite a while. Maybe try checkout the latest version?
