### ISSUE TITLE
can't override resetContentFrame()

### ISSUE THREAD

**Issue by shashwatp** [sima-11/SMSegmentView#14]
Any reason why resetContentFrame () is marked as private in SMSegment? There is no way to subclass it or any of its subclasses and relayout the various components. I could override layoutSubview but many of the properties are marked private too, such as imageView which makes even overriding layoutSubviews pretty useless.

I would like to draw the text over the image, both centered, and I cannot.

**Comment by sima-11** [comment]
@shashwatp Because that method is not supposed to be called directly. I'm currently working on a new version of it. Will take your request into consideration if that sounds okay?

**Comment by shashwatp** [comment]
@allenbryan11 thanks for update. If I may explain better what it was I trying to achieve you might find that easier to understand. I wanted to use a circular image as the background of the label. If there was a background image view property I might also have been able to achieve the same effect, using its contentMode property. So maybe if you consider adding that (it might already be there and I missed it somehow :-) that would be great too.

**Comment by sima-11** [comment]
@shashwatp Not sure if this would work for your, but maybe you can try the following code to assign the background colour with an image?:
segment.backgroundColor = UIColor(patternImage: {YOUR_IMAGE})

**Comment by sima-11** [comment]
@shashwatp Sorry for the incredibly long delay. I just moved everything in resetContentFrame() to the builtin public method layoutSubviews(), which would actually make more sense, I think. And this should also give you access to override the method, if you still need to. :P
