### ISSUE TITLE
didSelectSegmentAtindex

### ISSUE THREAD

**Issue by HideCode7** [sima-11/SMSegmentView#16]
HI great project, but i have a problem. 
I copy your code from my project and i put the segment on mapkit, and when i click in segment, method didSelectSegmentAtIndex, it is not called.

I update xcode from 7.3

**Comment by sima-11** [comment]
@HideCode7 If this is the delegate method that you called:
func segmentView(segmentView: SMBasicSegmentView, didSelectSegmentAtIndex index: Int){}
then probably you forgot to assign the delegate property?

**Comment by HideCode7** [comment]
I have this

`class ParkingPaymentGeo: UIViewController, SMSegmentViewDelegate, CLLocationManagerDelegate, MKMapViewDelegate {
     var segmentView: SMSegmentView!
    var margin: CGFloat = 10.0

```
override func viewDidLoad() {
    super.viewDidLoad()

    self.segmentView = SMSegmentView(frame: CGRect(x: self.margin, y: 120.0, width: self.view.frame.size.width - self.margin*2, height: 40.0), separatorColour: UIColor(white: 0.95, alpha: 0.3), separatorWidth: 0.5, segmentProperties: [keySegmentTitleFont: UIFont.systemFontOfSize(12.0), keySegmentOnSelectionColour: UIColor(red: 245.0/255.0, green: 174.0/255.0, blue: 63.0/255.0, alpha: 1.0), keySegmentOffSelectionColour: UIColor.whiteColor(), keyContentVerticalMargin: 10.0])

    self.segmentView.delegate = self

    self.segmentView.layer.cornerRadius = 5.0
    self.segmentView.layer.borderColor = UIColor(white: 0.85, alpha: 1.0).CGColor
    self.segmentView.layer.borderWidth = 1.0

    // Add segments
    self.segmentView.addSegmentWithTitle("Clip", onSelectionImage: UIImage(named: "car"), offSelectionImage: UIImage(named: "car"))
    self.segmentView.addSegmentWithTitle("Blub", onSelectionImage: UIImage(named: "walk"), offSelectionImage: UIImage(named: "walk"))
    self.segmentView.addSegmentWithTitle("Cloud", onSelectionImage: UIImage(named: "bike"), offSelectionImage: UIImage(named: "bike"))
    // Set segment with index 0 as selected by default
    //segmentView.selectSegmentAtIndex(0)

    self.view.addSubview(self.segmentView)
}

// SMSegment Delegate
func didSelectSegmentAtIndex(segmentIndex: Int) {
            print("Select segment at index: \(segmentIndex)")
}`
```

**Comment by sima-11** [comment]
@HideCode7 The name of the delegate method is not right. The one in your code is an old version of it. Try using this:
func segmentView(segmentView: SMSegmentView, didSelectSegmentAtIndex index: Int) {
        print("Select segment at index: (index)")
    }

**Comment by HideCode7** [comment]
If i used your solution i have this error:

Type 'ParkingPaymentGeo' does not conform to protocol 'SMSegmentViewDelegate'

**Comment by sima-11** [comment]
@HideCode7 It looks like you're using an old version of this framework. Maybe try re-downloading it?

**Comment by HideCode7** [comment]
@allenbryan11 I donwload your project again is it?

**Comment by sima-11** [comment]
@HideCode7 The delegate method has been changed to the one that I mentioned above months ago. So if the compiler complaints about using it, it should because that the framework is not up-to-date.

**Comment by HideCode7** [comment]
Yes i have the a new donload of your project and now it is update :). 
Problem solved.

Keep up the good work and thank you
