### ISSUE TITLE
touchesBegan and touchesEnded

### ISSUE THREAD

**Issue by PierreBresson** [sima-11/SMSegmentView#2]
I can't launch the demo because of this error. That's a shame because your segment view seems really promising and nice looking, thanks for sharing it ;)

![capture d ecran 2015-04-28 a 14 37 49](https://cloud.githubusercontent.com/assets/8709134/7369736/965134d8-edb4-11e4-944e-c0e5cc2736dd.png)

**Comment by sima-11** [comment]
@PierreLouisBresson Looks like the errors are caused by the change of Swift. Have updated the source code to make the errors away. Thanks for letting me know. :)
