### ISSUE TITLE
Update podspec for Cocoapods

### ISSUE THREAD

**Issue by kaylanx** [sima-11/SMSegmentView#21]
Please can you update the podspec on cocoapods to version 1.2.

At the moment we have to define it in our podfile like this...

pod 'SMSegmentView', :git => 'https://github.com/sima-11/SMSegmentView.git' 

It would be great if we could just use it without specifying the github url like this:

pod 'SMSegmentView', '~> 1.2'
Thanks

**Comment by sima-11** [comment]
@kaylanx Sure. I'll do this asap (probably this weekend if not distracted by other stuff). Will let you know once I've done it if that sounds ok?

**Comment by sima-11** [comment]
@kaylanx It doesn't seem that CocoaPods works very well with Swift 3 at the moment (haven't figured out how to fix the 119 errors returned by running "pod lib lint"). Will continue trying. But for now I'll have to leave it as what it is, I'm afraid. :(

**Comment by kaylanx** [comment]
Any plans to make this swift 3 compatible

**Comment by GreyEcologist** [comment]
Hey @sima-11 any updates on that?

**Comment by donpironet** [comment]
Can you please update the pod?

**Comment by cesarmtz93** [comment]
@sima-11 when will the pod be updated?

**Comment by cph2117** [comment]
@sima-11

**Comment by sima-11** [comment]
@kaylanx @GreyEcologist @donpironet @cesarmtz93 @cph2117 Sorry for the long delay. I finally updated the podspec file. :)
