### ISSUE TITLE
Horizontal Seg with icon on top of title

### ISSUE THREAD

**Issue by rdamore** [sima-11/SMSegmentView#23]
Hey, thanks for the great seg. Was just wondering if you were planning on adding the functionality of allowing the icon to be above the title? As in a horizontal seg controller but with icon on top of the title. Thanks!

**Comment by sima-11** [comment]
@rdamore I had some thoughts about it at the beginning of this project, but decided not to implement it as I don't really want this simple framework to go too complex, if that make sense?
If you do not have the requirement to change the organisationMode at run time, probably you can use an image which contains both icon and text for each segment?

**Comment by rdamore** [comment]
That makes sense. Thanks!
