### ISSUE TITLE
About SMSegmentViewDelegate

### ISSUE THREAD

**Issue by robpanes-space** [sima-11/SMSegmentView#26]
Hi Author, 

I use and love your work. Problem I have with the update for swift 3 is that "SMSegmentViewDelegate" error - undeclared type.

This also happens when I try to manually use the framework.

Can you somehow give me an idea what cause this, been looking and troubled for 2 days.

Hope you could help. 

Thanks,

**Comment by damozhang** [comment]
I noticed SMSegmentViewDelegate was removed when I upgrade to swift 3. 
There are an example  in the readme file and some example files.

You can try

```
segmentView.addTarget(
            self,
            action: #selector(YourViewController.selectSegmentInSegmentView(segmentView:)),
            for: .valueChanged
)
```

and add this method:

```
func selectSegmentInSegmentView(segmentView: SMSegmentView) {
        print("Select segment at index: \(segmentView.selectedSegmentIndex)")
}
```

that works for me.

**Comment by robpanes-space** [comment]
ok I will try
