### ISSUE TITLE
SMSegment does not handle touchesCancelled properly

### ISSUE THREAD

**Issue by simondec** [sima-11/SMSegmentView#28]
The `SMSegment` view handles `touchesBegan` and `touchesEnded`, but `touchesCancelled` is missing.  When adding this component in a scrollView, if you touch down on a segment and start scrolling the scrollView, the segment stays _highlighted_.

A workaround is to add the following extension to the project:
```swift
extension SMSegment {
    open override func touchesCancelled(_ touches: Set<UITouch>, with event: UIEvent?) {
        backgroundColor = isSelected ? self.appearance?.segmentOnSelectionColour : self.appearance?.segmentOffSelectionColour
    }
}
```

**Comment by sima-11** [comment]
@simondec Just added touchesCancelled. Thanks for pointing it out!
