### ISSUE TITLE
Does not conform to protocol SMSegmentViewDelegate

### ISSUE THREAD

**Issue by amycheong19** [sima-11/SMSegmentView#3]
Hi, my view controller is UIViewController but I cannot assign delegate to my UIViewController
![screen shot 2015-05-08 at 2 53 52 pm](https://cloud.githubusercontent.com/assets/9781961/7531831/2d4a0ec0-f592-11e4-9ce4-ca8bd7c2e2ce.png)

**Comment by sima-11** [comment]
@amycheong19 I think you should be able to get rid of the error by adding the following delegate method in your view controller:
func segmentView(segmentView: SMSegmentView, didSelectSegmentAtIndex index: Int) {
}

**Comment by amycheong19** [comment]
Thank you!
