### ISSUE TITLE
Title below image

### ISSUE THREAD

**Issue by filwiesner** [sima-11/SMSegmentView#38]
Hello,
First of all thank You for making this library. I needed to put both title and image there and you saved me! But the text I want to put in is too long to be displayed next to the image. Are you planning to make text below Image possible? It would really help me

Thanks again,
Filip

**Comment by sima-11** [comment]
Hey @w00d3nl3g, thanks for the feedback. And I'm glad that you chose my library. It's just at the moment I can spend very little time working on it due to other work. So probably will take a while before I can add this feature to it, I'm afraid. :(
Will let you know when this is done, though.

**Comment by filwiesner** [comment]
Hey, 
just issued a pull request on my solution to this problem. Sorry for not letting you work but I really want this feature :D  ( #39 )
