### ISSUE TITLE
Support multiple touches?

### ISSUE THREAD

**Issue by daviddelmonte** [sima-11/SMSegmentView#46]
Hi, your control works great (in 2021!), but I'd like to be able to select a segment multiple times -- I am thinking of using a segment to zoom in and another to zoom out. Is this possible?

**Comment by sima-11** [comment]
Hi @daviddelmonte, the library doesn't support it, I'm afraid. The best way for now is probably to fork it and then add new features on top.

**Comment by daviddelmonte** [comment]
Understood. Thanks for letting me know.
