### ISSUE TITLE
Implement initWithCoder method

### ISSUE THREAD

**Issue by paweljankowski** [sima-11/SMSegmentView#8]
This is a awesome component! But I can't initialize it from the Interface Builder because initWithCoder is not implemented. 
This is a weird behavior because the SMSegmentView class has properties marked as IBInspectable.

**Comment by Alserda** [comment]
Same issue here

**Comment by DonBaronFactory** [comment]
same here... I agree what is the sense of having IBInspectables but not being able to Instantiate it via Storyboard... please fix

**Comment by sima-11** [comment]
@paweljankowski @Alserda @cre8it Sorry guys, I know this has been quite a while. I have added initWithCoder into SMSegmentView class, so you should be able to setup the base view in Storyboard, but you probably still have to do the rest programatically (e.g. add a segment).

@cre8it I have removed all IBInspectables as it doesn't seem you would be able to see how the segmented control will look like from Storyboard at the current version of Xcode. It doesn't make much sense to me to specify some attributes in Storyboard without actually seeing them.
